spring.application.name=oauth2-jwt-thymeleaf
server.port=8081

spring.security.oauth2.client.registration.google.client-id=183634389819-1kp3m54pr7jatutj8nm40p6of8tnun8n.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
